@extends('common.footer')
@extends('common.footer-script')
@extends('common.header')
@extends('common.navbar')
<style>
        p{}
</style>
@section('content')
<section id="contact-banner" class="pad-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Terms and Conditions </h2>
            </div>
        </div>
    </div>
</section>
<section id="how-to-find" class="terms-condition">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="content-div">
                    <!-- <h2>Terms and Conditions</h2> -->
                    <p>“Callidus Consulting” having its registered office at Suite No. 301, Business Venue Building, Umm Hurair Road, P.O Box 121361,OudMetha, BurDubai, Dubai, United Arab Emirates, owns, operates and maintains the www.menainsurancekyc.com Website ("Site"). For the purpose of this Terms and conditions “Callidus Consulting” includes its subsidiaries, affiliates, divisions, contractors and all their data sources and suppliers.</p>

                    <p>The following are the terms of use that govern use of the Site ("Terms of Use"). By using the Site, you expressly agree to be bound by these Terms of Use and the www.menainsurancekyc.com privacy policy and to follow these Terms of Use and all applicable laws and regulations governing use of the Site. Callidus Consulting reserves the right to change these Terms of Use at any time, effective immediately upon posting on the Site. Please check this page of the Site periodically. We will note when there are updates to the Terms of Use at the bottom of the Terms of Use. If you violate these Terms of Use, Callidus Consulting may terminate your use of the Site, bar you from future use of the Site, and/or take appropriate legal action against you.</p>

                    <p>1.   LIMITED LICENSE. You are granted a limited, non-exclusive, revocable and non-transferable license to utilize and access the Site pursuant to the requirements and restrictions of these Terms of Use. Callidus Consulting may change, suspend, or discontinue any aspect of the Site at any time. Callidus Consulting may also, without notice or liability, impose limits on certain features and services or restrict your access to all or portions of the Site. You shall have no rights to the proprietary software and related documentation, if any, provided to you in order to access the Site. Except as provided in the Terms of Use, you shall have no right to directly or indirectly, own, use, loan, sell, rent, lease, license, sublicense, assign, copy, translate, modify, adapt, improve, or create any new or derivative works from, or display, distribute, perform, or in any way exploit the Site, or any of its contents (including software) in whole or in part.</p>

                    <p>2.   SITE OPERATION: United Arab Emirates is our Country of Domicile. Callidus Consulting controls this Site from the U.A.E. Callidus Consulting makes no representation that this Site is appropriate for use in other locations. If you use this Site from other locations, you are responsible for ensuring compliance with local laws. You may not use, export or re-export any materials from this Site in violation of any applicable laws or regulations, including, but not limited to any U.A.E export laws and regulations.</p>

                    <p>3.	APPLICABLE LAW. The Laws of the United Arab Emirates shall govern the use of the Site and the Terms of Use, without regards to conflict of laws and principles. All disputes arising in connection therewith shall be heard only by a court of competent jurisdiction in U.A.E.</p>

                    <p>4.	MULTI-CURRENCY PRICED TRANSACTION, the displayed price and currency selected by you, will be the same price and currency charged to the Card and printed on the Transaction Receipt.</p>

                    <p>5.	PURCHASES. Callidus Consulting accepts payment by Visa or Mastercard debit and credit cards in AED for its products and services. All online purchases are also governed by the terms and conditions of respective merchant service providers. Please review respective merchant service provider’s user agreement and privacy policy before entering any transaction. Interpretation: These Terms of Use supersede all other written and oral communications or agreements with regard to the subject matters discussed in these Terms of Use. A waiver or modification of these Terms of Use will only be effective if made in writing signed by an authorized officer of Callidus Consulting. All refunds will be made onto the original mode of payment.</p>

                    <p>6.   PRICE. The Website provides Users with a catalogue of list of services. Prices and taxes to buy the services are indicated in the catalogue. Callidus Consulting reserves the right to change its prices at any time by posting them online. The only prices applicable to per transactions are the ones in effect at the time the purchase is made. The prices include the taxes applicable on the date of the purchase and any change in the rate of these taxes will be reflected in the price of the templates in the catalogue. The total amount of the purchase, including all taxes, is indicated before the final confirmation of the purchase order. The payment of the full price must be made when the purchase is made.</p>

                    <p>7.	SUBSCRIPTION. Subject to the User purchasing sufficient Usage Rights in accordance with the terms and conditions of the Website, Callidus Consulting hereby grants to the User a non-exclusive, non-transferable right to permit Authorized Users to use the Service during the Subscription Term. The initial Subscription Term will commence and expire in accordance with the start date and end date set forth on the Order Form, unless earlier terminated. Thereafter, the Subscription shall automatically renew for additional one (1) year periods (or for such longer period as may be set forth on a renewal Order Form executed by the parties) unless either party gives written notice to the other of its intention not to renew the Subscription at least thirty (30) days prior to the expiration of the then-current Subscription Term.</p>

                    <p>8.	PAYMENT CONFIRMATION. By clicking “Submit,” you are consenting to receive a one-time confirmation of this payment electronically within 24 hrs to the Email address provided to us.</p>


                    <p>9.	DELIVERY OF SERVICES. By submitting a signed Service Order request, User agrees to take and pay for, and, by accepting the Service Order request, Callidus Consulting agrees to deliver the service(s) during the term described on the Service Order Summary: Requested Product will be delivered within two Days at the E Mail Address provided in the Request Form. Multiple Requests/orders are possible and may result in multiple postings to the cardholder’s monthly statement and multiple deliveries.</p>

                    <p>10.	SANCTIONED COUNTRIES. Callidus Consulting will not trade with or provide any services to individuals and companies owned or controlled by, or acting for or on behalf of, OFFICE FOREIGN ASSETS CONTROL (OFAC), the United Nations Security Council (UNSC) , the European Union(EU), Her Majesty’s Treasury (HMT) , or other relevant sanctions authority targeted countries AND individuals, groups, and entities, such as terrorists and narcotics traffickers designated under the OFAC, UNSC , EU and HMT Sanction programs that are not country specific.</p>

                    <p>11.	REPRESENTATIONS BY YOU. By visiting the Site, you represent, warrant and covenant that (a) you are at least 18 years old; (b) that all materials of any kind submitted by you to Callidus Consulting through the Site or for inclusion on the Site will not plagiarize, violate, or infringe upon the rights of any third-party including trade secret, copyright, trademark, trade dress, privacy, patent, or other personal or proprietary rights. The User using the website who are Minor /under the age of 18 shall not register as a User of the website and shall not transact on or use the website.</p>

                    <p>12.	PERMITTED USE. You agree that you are only authorized to visit, view and to retain a copy of pages of this Site for your own personal use, that you shall not duplicate, download, publish, modify or otherwise distribute the material on this Site for any purpose other than for personal use, unless otherwise specifically authorized by Callidus Consulting to do so. You also agree not to deep-link to the site for any purpose, unless specifically authorized by Callidus Consulting to do so. The content and software on this Site are the property of Callidus Consulting. The cardholder must retain a copy of transaction records and Merchant policies and rules.</p>

                    <p>13.	YOUR ACCOUNT. If you use Callidus Consulting Site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your account from any devices, and you agree to accept responsibility for all activities that occur under your account or password. The Site shall not be responsible or liable, directly or indirectly, in any way for any loss or damage of any kind incurred as a result of, or in connection with, your failure to comply with this section.</p>

                    <p>14.	NO COMMERCIAL USE. This Site may not be used by you for any commercial purposes such as to conduct sales of merchandise or services of any kind. You must obtain Callidus Consulting’s prior written consent to make commercial offers of any kind on the Site, whether by advertising, solicitations, links, or any other form of communication. Callidus Consulting will investigate and take appropriate legal action against anyone who violates this provision, including without limitation, removing the offending communication from the Site and barring such violators from use of the Site.</p>

                    <p>15.	LINKS AND SEARCH RESULTS. The Site may automatically produce search results that reference and/or link to third party sites throughout the World Wide Web. Callidus Consulting has no control over these sites or the content within them. Callidus Consulting does not guarantee, represent, or warrant that the content contained in the sites is accurate, legal and/or inoffensive. Callidus Consulting does not endorse the content of any third-party site, nor does it make any representation or warranty about these sites, including that they will not contain viruses or otherwise impact your computer. By using the Site to search for or link to another site, you agree and understand that you may not make any claim against Callidus Consulting for any damages or losses, whatsoever, resulting from your use of the Site to obtain search results or to link to another site. If you have a problem with a link from the Site, you may notify us at info@menainsurancekyc.com</p>

                    <p>16.	COPYRIGHT POLICY.Callidus Consulting may terminate the privileges of any user who uses this Site to unlawfully transmit copyrighted material without a license, express consent, valid defence, or fair use exemption to do so. If you submit information to this Site, you warrant that the information does not infringe the copyrights or other rights of third parties.</p>

                    <p>17.	INTELLECTUAL PROPERTY. Although Callidus Consulting is not responsible for the content, quality or accuracy of data provided by users, compilations of such data, text, information, and other materials made available to users through Callidus Consulting’s system. The On-line Materials are Callidus Consulting’s intellectual property and are protected by U.A.E and international intellectual property laws. The On-line Materials may not be copied or redistributed either in whole or in part without prior written consent of Callidus Consulting, except as expressly and specifically permitted under these Terms of Use.</p>

                    <p>18.	The On-line Materials are and will remain the exclusive property of Callidus Consulting. All rights, titles and interests in and to the On-line Materials will be and remain vested solely in Callidus Consulting. Under no circumstances will you have any right, directly or indirectly, to own, use, copy, loan, sell, rent, lease, license, sublicense, redistribute, assign, or otherwise convey the On- line Materials, or any rights thereto, except as expressly and specifically provided in the Terms of Use. Nothing in these Terms of Use will convey to you any right, title or interest, except that of a license with the express rights and subject to all limitations herein. Nothing in these Terms of Use grants you the right, directly or indirectly, to use the On-line Materials to create a product for resale or to use the On-line Materials in any way that competes with Callidus Consulting.</p>

                    <p>19.	You acknowledge and agree that Callidus Consulting will own all rights, titles and interests in and to any copy, translation, modification, adaptation, derivative work or improvement of the On- line Materials made by or for you. At Callidus Consulting’s request, you must execute, or obtain the execution of, any instrument that may be necessary to assign these rights, titles or interests to Callidus Consulting or perfect these rights, titles or interests in Callidus Consulting’s name.</p>

                    <p>20.	DISCLAIMER OF WARRANTY, LIMITATION OF DAMAGES. CALLIDUS CONSULTING MAKES NO WARRANTY OR REPRESENTATION OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTY OF TITLE OR NON-INFRINGEMENT OR IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT OR OTHER VIOLATION OF RIGHTS IN RELATION TO THE AVAILABILITY, ACCURACY, VALIDITY, RELIABILITY OR CONTENT OF THESE PAGES AND/OR THE SITE. CALLIDUS CONSULTING ALSO DOES NOT MAKE ANY REPRESENTATION OR WARRANTY REGARDING THE ACCURACY OR RELIABILITY OF ANY ADVICE, OPINION, STATEMENT OR OTHER INFORMATION THAT IS SUBMITTED, DISPLAYED OR UPLOADED THROUGH THE SITE BY ANY USER. CALLIDUS CONSULTING SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR FOR BUSINESS INTERRUPTION ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SITE, EVEN IF CALLIDUS CONSULTING HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. SOME JURISDICTIONS DO NOT ALLOW EXCLUSION OF CERTAIN WARRANTIES OR LIMITATIONS OF LIABILITY, SO THE ABOVE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. THE LIABILITY OF CALLIDUS CONSULTING WOULD IN SUCH CASE BE LIMITED TO THE GREATEST EXTENT OF LIABILITY PERMITTED BY LAW.</p>

                    <p>21.	VIOLATION OF TERMS OF USE. You understand and agree that in Callidus Consulting’s sole discretion, and without prior notice, Callidus Consulting may terminate your access to the Site, or exercise any other remedy available and remove any unauthorized user information, if Callidus Consulting believes that the information you provide has violated or is inconsistent with these Terms of Use, or violates the rights of Callidus Consulting, or any third party, or violates the law. You agree that monetary damages may not provide a sufficient remedy to Callidus Consulting for violations of these Terms of Use, and you consent to injunctive or other equitable relief for such violations. Callidus Consulting may release user information about you if required by law or subpoena.</p>

                    <p>22.	INDEMNITY. You agree to indemnify and hold Callidus Consulting, its subsidiaries, affiliates, officers, agents and other partners and employees, harmless from any loss, liability, claim or demand, including reasonable attorneys’ fees, made by any third party due to or arising out of or relating to your use of the Site, including also your use of the Site to provide a link to another site or to upload content or other information to the Site, or your breach of the Terms of Use.</p>

                    <p>23.	LICENCE GRANTED TO YOU. By providing materials to Callidus Consulting, including by submitting or uploading content or materials for use on the Site you represent and warrant that you or the owner of all rights to such content or materials has expressly granted Callidus Consulting an irrevocable world-wide right in all languages and in perpetuity to use and exploit all or any part of the content and materials provided by you. Callidus Consulting may publish and distribute any such submitted content or materials at its sole discretion by any method now existing or later developed. You agree that you shall waive all claims and have no recourse against Callidus Consulting for any alleged or actual infringement or misappropriation of any proprietary rights in any communication, content or material submitted to Callidus Consulting. Any communication or materials you send to Callidus Consulting will be treated as non- confidential and non-proprietary and may be disseminated or used by Callidus Consulting for any purpose, including, but not limited to, developing, creating, manufacturing, or marketing products or services.</p>

                    <p>24.	ADVERTISING. The Site may contain advertisements and/or sponsorships. The advertisers and/or sponsors that provide these advertisements and sponsorships are solely responsible for ensuring that the materials submitted for inclusion on the Site are accurate and comply with all applicable laws. Callidus Consulting is not responsible for the acts or omissions of any advertiser or sponsor.</p>

                    <p>25.	SEVERABILITY. If any provision of the Terms of Use is held to be invalid, void, or unenforceable, the remaining provisions shall nevertheless continue in full force and effect.</p>

                    <p>26.	FORCE MAJEURE. In the event Callidus Consulting is unable to perform its obligations under these terms of use because of acts of God, strikes, equipment or transmission failure or damage reasonably beyond its control, or other causes reasonably beyond its control, Callidus Consulting shall not be liable for damages to the other for any damages resulting from such failure to perform or otherwise from such causes.</p>

                    <p>27.	Headings & section titles in this Agreement are for convenience and do not define, limit, or extend any provision of this Agreement.</p>

                </div>
            </div>
        </div>
    </div>
</section>

@endsection
